# setting file
from worker.config import BROKER, BACKEND


BROKER_URL = BROKER

CELERY_RESULT_BACKEND = BACKEND

CELERY_RESULT_SERIALIZER = 'json'

CELERY_TASK_RESULT_EXPIRES = 60 * 60 * 24

CELERY_ACCEPT_CONTENT = ['json']
